Update alert_condition.html.markdown
When I do demo follow the example. Run command  `terraform apply` and get  the following message:  
    Error: `condition_scope` must be `application` or `instance`.
 it work well after i add a code line [condition_scope = "application"] . I think the example is missing  condition_scope